###
# Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    logical_enclosure_name: "Encl1"  # Set the name of a Logical Enclosure
    firmware_baseline_uri: "/rest/firmware-drivers/SPPgen9snap6_2016_0405_87"  # Set the URI of a Firmware Driver
    enclosure_uri: "/rest/enclosures/0000000000A66101" # Set the URI of an Enclosure
    enclosure_group_uri: "/rest/enclosure-groups/9fafc382-bbef-4a94-a9d1-05f77042f3ac" # Set the URI of an Enclosure Group

  tasks:
    # This operation is only available on HPE Synergy
    - name: Create a Logical Enclosure (available only on HPE Synergy)
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: present
        data:
            enclosureUris:
              - "{{ enclosure_uri }}"
            enclosureGroupUri: "{{ enclosure_group_uri }}"
            name: "{{ logical_enclosure_name }}"
      ignore_errors: true
      delegate_to: localhost

    - name: Update the firmware for the Logical Enclosure
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: firmware_updated
        data:
            name: "{{ logical_enclosure_name }}"
            firmware:
                firmwareBaselineUri: "{{ firmware_baseline_uri }}"
                firmwareUpdateOn: "EnclosureOnly"
                forceInstallFirmware: "false"
      ignore_errors: true
      delegate_to: localhost

    # This play is compatible with Synergy Enclosures
    - name: Update the firmware for the Logical Enclosure with the logical-interconnect validation set as true
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: firmware_updated
        data:
            name: "{{ logical_enclosure_name }}"
            firmware:
                firmwareBaselineUri: "{{ firmware_baseline_uri }}"
                firmwareUpdateOn: "EnclosureOnly"
                forceInstallFirmware: "false"
                validateIfLIFirmwareUpdateIsNonDisruptive: "true"
                logicalInterconnectUpdateMode: "Orchestrated"
                updateFirmwareOnUnmanagedInterconnect: "true"
      ignore_errors: true
      delegate_to: localhost

    - name: Update the Logical Enclosure configuration script
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: script_updated
        data:
            name: "{{ logical_enclosure_name }}"
            configurationScript: "# script (updated)"
      ignore_errors: true
      delegate_to: localhost

    - name: Generates a support dump for the Logical Enclosure
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: dumped
        data:
            name: "{{ logical_enclosure_name }}"
            dump:
              errorCode: "MyDump16"
              encrypt: "true"
              excludeApplianceDump: "false"
      delegate_to: localhost
    - debug: var=generated_dump_uri

    - name: Reconfigure all enclosures associated with logical enclosure
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: reconfigured
        data:
            name: "{{ logical_enclosure_name }}"
      delegate_to: localhost

    - name: Makes the logical enclosure consistent with the enclosure group
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: updated_from_group
        data:
            name: "{{ logical_enclosure_name }}"
      delegate_to: localhost

    - name: Update the Logical Enclosure changing the name attribute
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: present
        data:
            name: "{{ logical_enclosure_name }}"
            newName: "{{ logical_enclosure_name }} (renamed)"
      delegate_to: localhost

    - name: Rename the Logical Enclosure to its initial name
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: present
        data:
            name: "{{ logical_enclosure_name }} (renamed)"
            newName: "{{ logical_enclosure_name }}"
      delegate_to: localhost

    # This state is only available on HPE Synergy
    - name: Delete a Logical Enclosure (available only on HPE Synergy)
      oneview_logical_enclosure:
        config: "{{ config }}"
        state: absent
        data: '{{ logical_enclosure }}'
      ignore_errors: true
      delegate_to: localhost
